server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**
        - id: product-service
          uri: http://localhost:8084
          predicates:
            - Path=/products/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}

keycloak:
  url: http://localhost:8081/auth
  realm: tatti-app
  client-id: api-gateway
  client-secret: VWlB8B8HCZHSRm7yamIEKPyWv3hYDfjE
  username: admin
  password: 789123ewak
  grant-type: password

user:
  service:
    url: http://localhost:8082