spring:
  application:
    name: user-service
  main:
    web-application-type: reactive
#  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: root
  r2dbc:
    url: r2dbc:pool:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}?schema=user_schema
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    locations: classpath:db/migrations
    enabled: true
    baseline-on-migrate: true
    default-schema: user_schema
  codec:
    max-in-memory-size: 10MB
  cloud:
    discovery:
      enabled:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
        preferIpAddress: true

server:
  port: 8082

keycloak:
  url: http://localhost:8081/auth
  realm: tatti-app

logging:
  level:
    org.springframework: DEBUG

shop:
  product:
    url: http://localhost:8083/api/shop-products
