spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - AuthenticationFilter
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
          filters:
            - AuthenticationFilter
#        - id: catalog-service
#          uri: lb://catalog-service
#          predicates:
#            - Path=/api/shops/**
#          filters:
#            - AuthenticationFilter
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080
keycloak:
  url: ${KEYCLOAK_URL:https://tatti.pp.ua/auth}
  realm: tatti-app
  client-id: tatti-app
  client-secret: Ls5zJnfJ0KrmtRF4sVTzFeBcD8KGrv1J
  username: admin
  password: tatti2025
  grant-type: password
logging:
  level:
    org.springframework: DEBUG

user:
  service:
    url: http://localhost:8082