version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "2346:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  eureka-server:
    image: tanat443/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - postgres

  api-gateway:
    image: tanat443/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_URL: https://tatti.pp.ua/auth
    depends_on:
      - eureka-server
      - user-service
      - order-service
      - product-service

  user-service:
    image: tanat443/user-service:latest
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: root
      KEYCLOAK_URL: https://tatti.pp.ua/auth
    depends_on:
      - postgres
      - eureka-server

  order-service:
    image: tanat443/order-service:latest
    container_name: order-service
    ports:
      - "8084:8084"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: root
      KEYCLOAK_URL: https://tatti.pp.ua/auth
    depends_on:
      - postgres
      - eureka-server

  product-service:
    image: tanat443/product-service:latest
    container_name: product-service
    ports:
      - "8083:8083"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: root
      KEYCLOAK_URL: https://tatti.pp.ua/auth
    depends_on:
      - postgres
      - eureka-server

volumes:
  pgdata:
