server:
  port: ${PORT:8080}

spring:
  r2dbc:
    url: r2dbc:pool:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:qwerty}

  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:qwerty}
    locations: classpath:db/migrations
    enabled: true
    baseline-on-migrate: true
