server:
  port: ${PORT:8084}

spring:
  application:
    name: order-service
  r2dbc:
    url: r2dbc:pool:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}?schema=order_schema
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}

  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    locations: classpath:db/migrations
    enabled: true
    baseline-on-migrate: true
    default-schema: order_schema

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true